"""
LORE Research Context — Full BTC market brief for CrypNuevo mentor.

Combines market data + funding + OI + liquidations + regime into one
markdown brief ready to paste into the mentor chat.

This is the script to run before every chart review session.

Usage:
    python tools/lore/research_context.py
    python tools/lore/research_context.py --timeframe 1h
    python tools/lore/research_context.py --timeframe 4h --lookback 72
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime, timezone
from io import StringIO

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

# Import the individual fetchers
from tools.lore.fetch_market import fetch_ohlcv, fetch_funding, fetch_oi, _summarize_list
from tools.lore.fetch_liquidations import _try_endpoints as liq_try, _LIQ_ENDPOINTS
from tools.lore.fetch_regime import _try_endpoints as regime_try, _REGIME_ENDPOINTS, _extract_regime_label
import tools.lore.client as lore


def _safe_latest(data: dict | None) -> dict:
    if not data:
        return {}
    raw = data.get("data", {})
    summary = _summarize_list(raw)
    return summary.get("latest", {})


def _funding_bias(latest: dict) -> str:
    """Interpret funding rate as bullish/bearish/neutral."""
    for key in ("funding_rate", "rate", "value", "funding"):
        if key in latest:
            rate = float(latest[key])
            if rate > 0.01:
                return f"+{rate:.4f} (POSITIVE — market is paying longs; potential short squeeze territory)"
            elif rate < -0.01:
                return f"{rate:.4f} (NEGATIVE — market is paying shorts; potential short squeeze setup)"
            else:
                return f"{rate:.4f} (NEUTRAL — no strong funding bias)"
    return "unknown"


def _oi_bias(data: dict | None) -> str:
    """Detect OI expansion or contraction."""
    if not data:
        return "unknown"
    raw = data.get("data", {})
    summary = _summarize_list(raw)
    oldest = summary.get("oldest", {})
    latest = summary.get("latest", {})
    for key in ("oi", "open_interest", "value", "total"):
        if key in oldest and key in latest:
            try:
                old_val = float(oldest[key])
                new_val = float(latest[key])
                pct = ((new_val - old_val) / old_val) * 100 if old_val else 0
                direction = "EXPANDING" if pct > 2 else "CONTRACTING" if pct < -2 else "FLAT"
                return f"{direction} ({pct:+.1f}% over the lookback period)"
            except (TypeError, ValueError):
                pass
    return "unknown (check raw data)"


def main():
    ap = argparse.ArgumentParser(description="Full BTC context brief from LORE")
    ap.add_argument("--timeframe", default="4h",
                    choices=["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
                    help="Candle timeframe (default: 4h)")
    ap.add_argument("--lookback", type=int, default=50,
                    help="Number of periods for OHLCV/funding/OI (default: 50)")
    args = ap.parse_args()

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    print(f"# LORE BTC Research Context — {args.timeframe.upper()} — {now}")
    print()
    print("*Generated by `tools/lore/research_context.py`. Paste into mentor chat before chart review.*")
    print()
    print("---")
    print()

    # --- OHLCV ---
    print("## Price / OHLCV")
    sys.stderr.write("Fetching OHLCV...\n")
    ohlcv = fetch_ohlcv(args.timeframe, args.lookback)
    if ohlcv:
        latest = _safe_latest(ohlcv)
        print(f"- Endpoint: `{ohlcv['endpoint']}`")
        if latest:
            close = latest.get("close") or latest.get("c") or latest.get("price") or "—"
            high = latest.get("high") or latest.get("h") or "—"
            low = latest.get("low") or latest.get("l") or "—"
            ts = latest.get("timestamp") or latest.get("time") or latest.get("t") or "—"
            print(f"- Last close: **{close}**")
            print(f"- Last high: {high} | Last low: {low}")
            print(f"- Candle timestamp: {ts}")
        else:
            print("- Data received — run with `--raw` flag via fetch_market.py for full candles")
    else:
        print("- Not available (endpoint not yet discovered — run `discover.py`)")
    print()

    # --- FUNDING ---
    print("## Funding Rate")
    sys.stderr.write("Fetching funding...\n")
    funding = fetch_funding(args.lookback)
    if funding:
        latest = _safe_latest(funding)
        bias = _funding_bias(latest)
        print(f"- Endpoint: `{funding['endpoint']}`")
        print(f"- Current: **{bias}**")
        print()
        print("> **CrypNuevo rule:** Negative funding + price at support = potential long squeeze reversal setup.")
        print("> Extreme positive funding + price at resistance = potential short squeeze setup.")
    else:
        print("- Not available (endpoint not yet discovered)")
    print()

    # --- OPEN INTEREST ---
    print("## Open Interest")
    sys.stderr.write("Fetching OI...\n")
    oi = fetch_oi(args.lookback)
    if oi:
        oi_bias = _oi_bias(oi)
        print(f"- Endpoint: `{oi['endpoint']}`")
        print(f"- Trend: **{oi_bias}**")
        print()
        print("> **CrypNuevo rule:** OI expanding + price rising = longs building (MM building shorts).")
        print("> OI expanding + price falling = shorts building (MM building longs).")
        print("> OI contracting = positions closing; watch for squeeze.")
    else:
        print("- Not available (endpoint not yet discovered)")
    print()

    # --- LIQUIDATIONS ---
    print("## Liquidation Clusters")
    sys.stderr.write("Fetching liquidations...\n")
    liq_params = {"symbol": "BTC", "hours": 48, "limit": 50}
    liq_result = liq_try(_LIQ_ENDPOINTS, liq_params)
    if liq_result:
        ep, data = liq_result
        print(f"- Endpoint: `{ep}`")
        # Try to extract top clusters
        clusters = []
        if isinstance(data, list):
            clusters = data[:5]
        elif isinstance(data, dict):
            for key in ("clusters", "liquidations", "data", "levels"):
                if key in data and isinstance(data[key], list):
                    clusters = data[key][:5]
                    break
        if clusters:
            print("- Top clusters:")
            for c in clusters:
                print(f"  - {json.dumps(c)}")
        else:
            print("- Data received — run `fetch_liquidations.py` for full breakdown")
        print()
        print("> **CrypNuevo rule:** Densest untaken liquidation cluster = price magnet.")
        print("> Long clusters above price = resistance magnets. Short clusters below = support magnets.")
        print("> A cluster is 'taken' when price wicks through it.")
    else:
        print("- Not available (endpoint not yet discovered)")
    print()

    # --- REGIME ---
    print("## Volatility Regime")
    sys.stderr.write("Fetching regime...\n")
    regime_result = regime_try(_REGIME_ENDPOINTS, {"symbol": "BTC"})
    if regime_result:
        ep, data = regime_result
        regime = _extract_regime_label(data)
        print(f"- Endpoint: `{ep}`")
        print(f"- Current regime: **{regime or 'unknown'}**")
        print()
        regime_guidance = {
            "trending_low_vol": "Range extreme deviation and sweep setups are highest probability.",
            "trending_high_vol": "Wick fills and imbalance continuation setups dominate.",
            "ranging": "Full range playbook — watch for Three Taps, sweep of extremes.",
            "choppy": "NO SETUP — flat/choppy = no man's land. Default to watchlist only.",
        }
        matched = next((v for k, v in regime_guidance.items() if regime and k in regime), None)
        if matched:
            print(f"> **CrypNuevo setup guidance for this regime:** {matched}")
    else:
        print("- Not available (endpoint not yet discovered)")
    print()

    print("---")
    print()
    print("## How To Use This Brief")
    print()
    print("Paste this entire block into your CrypNuevo mentor chat before sharing a chart.")
    print("The mentor will use it to populate:")
    print("- **Section 3 (What Is Still Missing):** e.g. 'Long liquidation cluster at $X still untaken'")
    print("- **Section 5 (Risk Management):** e.g. 'OI expanding with negative funding — adds confluence to long bias'")
    print()
    print("For historical validation, run: `python tools/lore/research_setup.py`")


if __name__ == "__main__":
    main()
